#!/bin/bash

rm CMakeCache.txt
cmake -DCMAKE_TOOLCHAIN_FILE=cmake/Toolchain-mingw32.cmake  -DCMAKE_INSTALL_PREFIX=. -DFREETYPE_LIBRARY=extlibs/libs-mingw/libfreetype.a -DSFMLDIR=lib/ -DCMAKE_INCLUDE_PATH=/usr/local/include


